plugins {
	//id("fish.cichlidmc.cichlid-gradle")
	id 'java'
	id 'maven-publish'
	id "com.modrinth.minotaur" version "2.+"
	id "org.spongepowered.gradle.vanilla" version "0.2.1-20241107.194040-91"

}

sourceCompatibility = JavaVersion.VERSION_21
targetCompatibility = JavaVersion.VERSION_21

archivesBaseName = project.archives_base_name
version = project.mod_version + "+" + project.minecraft_version
group = project.maven_group

repositories {
	mavenCentral()
	mavenCentral()
	maven { url = "https://mvn.devos.one/releases" }
	maven { url = "https://libraries.minecraft.net" }
	//cichlid.releases()
	//minecraft.libraries()
	//minecraft.versions()
}

configurations{
	loader
}

dependencies {
	/*implementation(minecraft.of {
		client()
		version(project.minecraft_version)
	})

	compileOnly(cichlid.api(project.loader_version))
	cichlidRuntime(cichlid.runtime(project.loader_version))*/

	implementation 'fish.cichlidmc:cichlid:0.3.2'
	loader 'fish.cichlidmc:cichlid:0.3.2'
}

minecraft {
	version("1.21.5") // or: latestRelease() or latestSnapshot()
	runs {
		server() {
			//jvmArgs("-javaagent:" + configurations.loader.resolvedConfiguration.files())
		}
		client() {
			//jvmArgs("-javaagent:" + configurations.loader.resolvedConfiguration.files())
		}
	}
}

//cichlid {
//	runs {
//		register("client") {
//			version = project.minecraft_version
//		}
//        register("client 1.21.4") {
//            version = "1.21.4"
//            template = "client"
//        }

//        register("serverButCooler") {
//            template = "server"
//            programArgs.get().remove("nogui")
//            jvmArg("-Dmixin.debug.export=true")
//        }
//
//        configureEach {
//            version = minecraftVersion
//            jvmArg("-Dmixin.debug.export=true")
//        }
//	}
//}

processResources {
	inputs.property "version", project.version

	filesMatching('cichlid.mod.json') {
		expand "version": project.version
	}
}

// ensure that the encoding is set to UTF-8, no matter what the system default is
// this fixes some edge cases with special characters not displaying correctly
// see http://yodaconditions.net/blog/fix-for-java-file-encoding-problems-with-gradle.html
tasks.withType(JavaCompile) {
	options.encoding = "UTF-8"
}

jar {
	from "LICENSE"
}
def env = System.getenv()

// configure the maven publication
publishing {
	publications {
		mavenJava(MavenPublication) {
			mavenJava(MavenPublication) {
				groupId = rootProject.maven_group
				artifactId = project.archivesBaseName
				version = project.version

				from components.java
			}
		}
	}

	// See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
	repositories {
		// Add repositories to publish to here.
		// Notice: This block does NOT have the same function as the block in the top level.
		// The repositories here will be used for publishing your artifact, not for
		// retrieving dependencies.
		repositories {
			if (env.MAVEN_URL) {
				maven {
					credentials {
						username env.MAVEN_USERNAME
						password env.MAVEN_PASSWORD
					}
					url env.MAVEN_URL
				}
			} else {
				mavenLocal()
			}
		}
	}
}

if (System.getenv("MODRINTH")) {
	modrinth {
		token = System.getenv("MODRINTH")
		projectId = '5e65FGXQ'
		versionNumber = "" + version
		changelog = System.getenv("CHANGELOG")
		// On fabric, use 'remapJar' instead of 'jar'
		uploadFile = remapJar
		gameVersions = [((String) project.minecraft_version)]
		loaders = ["other"]
	}

	remapJar {
		finalizedBy project.tasks.modrinth
	}
}
